name: WF 4 Docker Build and Test
on:
  pull_request:
    branches:
      - main
    paths:
      - "docker/*"

jobs:
  code-unit-testing:
    runs-on: ubuntu-latest

    outputs:
      status: ${{ job.status }}

    defaults:
      run:
        working-directory: docker

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4.1.5

      - name: Run installation of dependencies commands
        run: npm install

      - name: Run unit testing command
        run: |
          npm test

  build-and-scan-image:
    runs-on: ubuntu-latest
    needs: [code-unit-testing]

    outputs:
      status: ${{ job.status }}

    defaults:
      run:
        working-directory: docker

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4.1.5

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Docker build and tag
        run: |
          docker build -t simple-docker-image:latest .

      - name: Run image scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: "simple-docker-image:latest"
          format: "table"
          # exit-code: '1'
          ignore-unfixed: true
          vuln-type: "os,library"
          severity: "MEDIUM,HIGH,CRITICAL"
          output: "docker-image-scan.json"

      - name: Upload Docker Trivy Report
        uses: actions/upload-artifact@v4.3.0
        with:
          name: docker-image-scan
          path: docker-image-scan.json

  build_summary:
    needs: [code-unit-testing, build-and-scan-image]
    runs-on: ubuntu-latest
    steps:
      - name: Adding markdown
        run: |
          CODE_UNIT_STATUS=${{ needs.code-unit-testing.outputs.status }}
          DOCKER_SCAN_STATUS=${{ needs.build-and-scan-image.outputs.status }}

          echo '## 🚀 Preparing Build Summary 🚀' >> $GITHUB_STEP_SUMMARY
          echo '' >> $GITHUB_STEP_SUMMARY

          echo "| Job Name        | Status |" >> $GITHUB_STEP_SUMMARY
          echo "|-----------------|--------|" >> $GITHUB_STEP_SUMMARY
          echo "| code-scan       | $CODE_SCAN_STATUS |" >> $GITHUB_STEP_SUMMARY
          echo "| docker-scan       | $DOCKER_SCAN_STATUS |" >> $GITHUB_STEP_SUMMARY
